# Generated by Django 3.0.3 on 2022-01-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bean_from', models.CharField(max_length=255)),
                ('price', models.IntegerField(max_length=20)),
            ],
        ),
    ]
