# Generated by Django 4.0.2 on 2022-02-12 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ilovecoffee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
