# Generated by Django 4.0.2 on 2022-02-12 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ilovecoffee', '0002_csvhandler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CsvHandler',
        ),
    ]
